"""
Generate CAAP-1 journal output against the x402-receipts v0.5.1 vector corpus.

Stelar pointed out (x402-foundation/x402#2833) that the funded/delivered/settled
fixtures already exist in x402-receipts commit debc94f, under vectors/. This
script consumes those REAL vectors through CAAP-1's reference implementation and
publishes the expected journal entry for each — so the accounting layer is
conformance-tested against the same corpus as the verification layer.

The point pair is pass-settled-delivered vs neg-funded-not-delivered: they share
the SAME real Base tx (0xdeb5872c…, $0.005 USDC), and differ only in the delivery
predicate — delivered/HTTP200 vs failed/HTTP502. CAAP-1 books the first as clean
expense and routes the second to the exception queue. That pair is the sharpest
demonstration of why accounting can't just read the settlement: the money moved
identically in both; only delivery differs, and only the receipt carries that.

Output: spec/caap1_against_receipts/EXPECTED.md — a human-readable table of
(vector -> CAAP-1 journal entry), plus expected.json for machine diffing.
"""
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from counterralib.receipts import receipt_to_journal, ReceiptError

VDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "caap1_against_receipts")

# A minimal chart of accounts for the demonstration (real CAAP-1 uses config).
EXPENSE_ACCOUNTS = {
    "AI & Compute Services": "6420 - AI & Compute Services",
    "Data & Research Services": "6410 - Data & Research Services",
    "Uncategorized": "6490 - Uncategorized Agent Spend",
}


def caap1_for_vector(vec):
    """Run one receipts vector through CAAP-1. Returns (entry, note)."""
    receipt = vec.get("receipt")
    if not receipt:
        return None, "vector carries no receipt object"
    try:
        j = receipt_to_journal(receipt, registry={}, expense_accounts=EXPENSE_ACCOUNTS)
    except ReceiptError as e:
        return None, f"CAAP-1 could not consume: {e}"
    return j, None


def main():
    vectors = []
    for path in sorted(glob.glob(os.path.join(VDIR, "*.json"))):
        if os.path.basename(path) in ("expected.json",):
            continue  # don't read our own generated output as a vector
        try:
            data = json.load(open(path))
        except Exception:
            continue
        if isinstance(data, dict) and "receipt" in data:  # real vectors only
            vectors.append(data)

    rows = []
    for v in vectors:
        vid = v.get("id", os.path.basename(str(v)))
        entry, note = caap1_for_vector(v)
        if entry is None:
            rows.append({"vector": vid, "caap1": None, "note": note})
            continue
        rows.append({
            "vector": vid,
            "caap1": {
                "date": entry["date"],
                "debit_account": entry["debit_account"],
                "credit_account": entry["credit_account"],
                "amount_usd": entry["amount_usd"],
                "delivery_status": entry["delivery_status"],
                "http_status": entry["http_status"],
                "bookable": entry["bookable"],
                "exception_reason": entry["exception_reason"],
                "tx_hash": entry["tx_hash"],
            },
            "note": None,
        })

    # machine-diffable
    with open(os.path.join(VDIR, "expected.json"), "w") as f:
        json.dump({"spec": "CAAP-1", "aligned_to": "x402-receipts v0.5.1 (debc94f)",
                   "rows": rows}, f, indent=2)

    # human-readable
    lines = [
        "# CAAP-1 journal output against x402-receipts v0.5.1 vectors",
        "",
        "Generated by `spec/caap1_against_receipts.py` from the vector corpus in",
        "x402-receipts commit `debc94f` (v0.5.1). Each row is the journal entry",
        "CAAP-1's reference consumer produces from that receipt.",
        "",
        "The key pair is **pass-settled-delivered** vs **neg-funded-not-delivered**:",
        "same real Base tx, same $0.005 settlement — CAAP-1 books the first as clean",
        "expense and routes the second to the exception queue, because delivery failed.",
        "The chain shows an identical payment in both; only the receipt distinguishes them.",
        "",
        "## Honest scope note (a finding from running this corpus)",
        "",
        "CAAP-1 v1.0.0-draft decides bookability from **delivery status + HTTP code",
        "only**. It assumes it is handed a receipt the caller has already VERIFIED",
        "(via x402-receipts `verifyReceiptFull`). So the negatives that fail for",
        "*verification* reasons rather than *delivery* reasons — `neg-delivered-not-settled`",
        "(settlement predicate fails), `neg-settled-to-expected-solver-mismatch`",
        "(payee/solver mismatch), `neg-countersig-not-payer` (bad countersig),",
        "`neg-leaf-not-in-anchored-root` (anchor proof fails) — still show BOOKABLE",
        "here, because CAAP-1 doesn't re-run verification; it trusts the caller did.",
        "",
        "That is a real boundary this corpus exposed. **CAAP-1 v1.1 will add a",
        "normative rule: a receipt that fails `verifyReceiptFull` MUST be an",
        "exception (`unverified-receipt`), never booked** — so the books only ever",
        "post verified receipts. The verification verdict is an input CAAP-1 requires,",
        "not something it recomputes; this table shows the delivery-layer behavior in",
        "isolation.",
        "",
        "| Vector | Amount | Delivery / HTTP | CAAP-1 result (delivery layer only) |",
        "|---|---|---|---|",
    ]
    for r in rows:
        c = r["caap1"]
        if not c:
            lines.append(f"| {r['vector']} | — | — | (not consumed: {r['note']}) |")
            continue
        result = ("BOOKABLE → " + c["debit_account"]) if c["bookable"] \
            else ("EXCEPTION — " + (c["exception_reason"] or "review"))
        lines.append(f"| {r['vector']} | ${c['amount_usd']:.6f} | "
                     f"{c['delivery_status']}/{c['http_status']} | {result} |")
    lines.append("")
    lines.append("_CAAP-1 aligned to x402-receipts v0.5.1 (`debc94f`). "
                 "Field names pinned per #2833._")

    with open(os.path.join(VDIR, "EXPECTED.md"), "w") as f:
        f.write("\n".join(lines))

    print("\n".join(lines))


if __name__ == "__main__":
    main()
